# Natasha Eva Dwi Nurdiyanti
# 2311110005

In [28]:
# Mengimpor library yang dibutuhkan
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [29]:
# Memasukan file dataset dan menampilkannya
file_path = "/content/CAD-Dataset.xlsx"
df = pd.read_excel(file_path)
df.head()

,No,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,1,53,90,175,Male,?,n,Y,Y,n,...,4.7,141,5700,39,52,261,50,0,N,Cad
1,2,67,70,157,Fmale,NaN,n,Y,n,n,...,4.7,156,7700,38,55,165,40,4,N,Cad
2,3,54,54,164,Male,NaN,n,n,Y,n,...,4.7,139,7400,38,60,230,40,2,mild,Cad
3,4,66,67,158,Fmale,NaN,n,Y,n,n,...,4.4,142,13000,18,72,?,55,0,Severe,Normal
4,5,50,87,153,Fmale,NaN,n,Y,n,n,...,4.0,140,9200,55,39,274,50,0,Severe,Normal

In [30]:
# Dikarenakan dalam dataset terdapat data berupa '?' maka perlu diubah menjadi NaN agar missing value nya dapat terdeteksi semua
# Mengubah semua '?' menjadi NaN agar bisa dideteksi sebagai missing values
df.replace('?', np.nan, inplace=True)

<ipython-input-30-1a5ed2694e9e>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('?', np.nan, inplace=True)

In [31]:
# Menampilkan jumlah missing value
df.isnull().sum()

No                         0
Age                        0
Weight                     0
Length                     0
Sex                        0
BMI                      303
DM                         1
HTN                        0
Current Smoker             7
EX-Smoker                  0
FH                         0
Obesity                    0
CRF                        2
CVA                        5
Airway disease             0
Thyroid Disease            2
CHF                        0
DLP                        0
BP                         2
PR                         0
Edema                      0
Weak Peripheral Pulse      0
Lung rales                 0
Systolic Murmur            0
Diastolic Murmur           0
Typical Chest Pain         0
Dyspnea                    0
Function Class             0
Atypical                   0
Nonanginal                 4
Exertional CP              9
LowTH Ang                  4
Q Wave                     2
St Elevation               1
St Depression              2
Tinversion                 0
LVH                        0
Poor R Progression         0
FBS                        2
CR                         0
TG                         1
LDL                        2
HDL                        0
BUN                        1
ESR                        1
HB                         0
K                          0
Na                         0
WBC                        0
Lymph                      0
Neut                       0
PLT                        1
EF-TTE                     0
Region RWMA                0
VHD                        0
Cath                       0
dtype: int64

In [44]:
# Dikarenakan terdapat missing value pada data maka akan diisi dengan modus
for column in df.columns:
    if df[column].isnull().sum() > 0:  # Hanya memproses kolom yang memiliki missing values
        mode_series = df[column].mode()  # Mengambil mode (modus)

        if not mode_series.empty:  # Pastikan mode tidak kosong sebelum mengambil nilai
            mode_value = mode_series[0]  # Ambil nilai modus pertama
            df[column].fillna(mode_value, inplace=True)  # Mengisi missing values dengan modus

In [33]:
# Dikarenakan pada kolom BMI tidak terdapat data maka kolom tersebut akan dihapus
df.drop(columns=['BMI'], inplace=True)

In [34]:
df

,No,Age,Weight,Length,Sex,DM,HTN,Current Smoker,EX-Smoker,FH,...,K,Na,WBC,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,Cath
0,1,53,90,175,Male,n,Y,Y,n,n,...,4.7,141,5700,39,52,261.0,50,0,N,Cad
1,2,67,70,157,Fmale,n,Y,n,n,n,...,4.7,156,7700,38,55,165.0,40,4,N,Cad
2,3,54,54,164,Male,n,n,Y,n,n,...,4.7,139,7400,38,60,230.0,40,2,mild,Cad
3,4,66,67,158,Fmale,n,Y,n,n,n,...,4.4,142,13000,18,72,170.0,55,0,Severe,Normal
4,5,50,87,153,Fmale,n,Y,n,n,n,...,4.0,140,9200,55,39,274.0,50,0,Severe,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,58,84,168,Male,n,n,n,n,n,...,4.8,146,8500,34,58,251.0,45,0,N,Cad
299,300,55,64,152,Fmale,n,n,n,n,n,...,4.0,139,11400,16,80,377.0,40,0,mild,Normal
300,301,48,77,160,Fmale,n,Y,n,n,Y,...,4.0,140,9000,35,55,279.0,55,0,N,Normal
301,302,57,90,159,Fmale,Y,n,n,n,n,...,3.8,141,3800,48,40,208.0,55,0,N,Normal
302,303,56,85,170,Fmale,n,Y,Y,n,n,...,4.4,147,6000,32,55,302.0,55,0,N,Cad

In [41]:
# Mengubah semua kolom kategorikal menjadi numerik 0 dan 1
kolom_kategorikal = [
    'Sex', 'DM', 'HTN', 'Current Smoker', 'EX-Smoker', 'FH', 'Obesity', 'CRF', 'CVA',
    'Airway disease', 'Thyroid Disease', 'ChF', 'DLP', 'Edema', 'Weak Peripheral Pulse',
    'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Dyspnea', 'Atypical',
    'Nonanginal', 'Exertional', 'LowTH Ang', 'LVH', 'Poor R Progression', 'VHD', 'Cath'
]

for col in kolom_kategorikal:
    if col in df.columns:
        unique_values = df[col].dropna().unique()

        if len(unique_values) == 2:  # Label Encoding
            # Mengkonversi menjadi 0 untuk N dan 1 untuk Y
            df[col] = df[col].map({unique_values[0]: 1, unique_values[1]: 0})

        elif len(unique_values) > 2:  # One-Hot Encoding
            df = pd.get_dummies(df, columns=[col], drop_first=True, dtype=int) # Specify dtype for one-hot columns

# Mengisi NaN dengan 0 sebelum konversi ke integer
df.fillna(0, inplace=True)

# Mengganti data non-numerik dengan 0
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0) # Handle errors, then fill NaN

# Konversi semua kolom boolean menjadi integer (0 dan 1)
df = df.astype(int)

In [42]:
df

,No,Age,Weight,Length,Sex,DM,HTN,FH,Obesity,CRF,...,EF-TTE,Region RWMA,Cath,Current Smoker_\,Current Smoker_n,EX-Smoker_n,EX-Smoker_z,VHD_N,VHD_Severe,VHD_mild
0,1,53,90,175,1,1,1,1,1,1,...,50,0,1,0,0,1,0,1,0,0
1,2,67,70,157,0,1,1,1,1,1,...,40,4,1,0,1,1,0,1,0,0
2,3,54,54,164,1,1,0,1,0,1,...,40,2,1,0,0,1,0,0,0,1
3,4,66,67,158,0,1,1,1,1,1,...,55,0,0,0,1,1,0,0,1,0
4,5,50,87,153,0,1,1,1,1,1,...,50,0,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,58,84,168,1,1,0,1,1,1,...,45,0,1,0,1,1,0,1,0,0
299,300,55,64,152,0,1,0,1,1,1,...,40,0,0,0,1,1,0,0,0,1
300,301,48,77,160,0,1,1,0,1,1,...,55,0,0,0,1,1,0,1,0,0
301,302,57,90,159,0,0,0,1,1,1,...,55,0,0,0,1,1,0,1,0,0
302,303,56,85,170,0,1,1,1,1,1,...,55,0,1,0,0,1,0,1,0,0

In [38]:
# Melakuakan normalisasi
from sklearn.preprocessing import MinMaxScaler

# Mengisi NaN dengan 0 agar tidak error saat normalisasi
df.fillna(0, inplace=True)

# Normalisasi dengan Min-Max Scaling (0 - 1)
scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

# Menampilkan 5 baris pertama hasil normalisasi
print("\nData setelah normalisasi:\n", df_normalized.head())

Data setelah normalisasi:
          No       Age    Weight    Length  Sex   DM  HTN   FH  Obesity  CRF  \
0  0.000000  0.410714  0.583333  0.729167  1.0  1.0  1.0  1.0      1.0  1.0
1  0.003311  0.660714  0.305556  0.354167  0.0  1.0  1.0  1.0      1.0  1.0
2  0.006623  0.428571  0.083333  0.500000  1.0  1.0  0.0  1.0      0.0  1.0
3  0.009934  0.642857  0.263889  0.375000  0.0  1.0  1.0  1.0      1.0  1.0
4  0.013245  0.357143  0.541667  0.270833  0.0  1.0  1.0  1.0      1.0  1.0

   ...    EF-TTE  Region RWMA  Cath  Current Smoker_\  Current Smoker_n  \
0  ...  0.777778          0.0   1.0               0.0               0.0
1  ...  0.555556          1.0   1.0               0.0               1.0
2  ...  0.555556          0.5   1.0               0.0               0.0
3  ...  0.888889          0.0   0.0               0.0               1.0
4  ...  0.777778          0.0   0.0               0.0               1.0

   EX-Smoker_n  EX-Smoker_z  VHD_N  VHD_Severe  VHD_mild
0          1.0          0.0    1.0         0.0       0.0
1          1.0          0.0    1.0         0.0       0.0
2          1.0          0.0    0.0         0.0       1.0
3          1.0          0.0    0.0         1.0       0.0
4          1.0          0.0    0.0         1.0       0.0

[5 rows x 59 columns]